"""Sample fleet and reviews used when demo data is enabled."""

DEMO_FLEET = [
    {
        "car_id": "car_lambo_aventador",
        "brand": "Lamborghini",
        "model": "Aventador SVJ",
        "category": "Sports",
        "price_per_day": 1450.0,
        "fuel_type": "Petrol",
        "transmission": "Automatic",
        "seats": 2,
        "rating": 4.9,
        "reviews_count": 128,
        "available": True,
        "image": "https://images.unsplash.com/photo-1544636331-e26879cd4d9b?w=1200&q=80",
        "gallery": [
            "https://images.unsplash.com/photo-1544636331-e26879cd4d9b?w=1200&q=80",
            "https://images.unsplash.com/photo-1503376780353-7e6692767b70?w=1200&q=80",
            "https://images.unsplash.com/photo-1607853202273-797f1c22a38e?w=1200&q=80",
        ],
        "features": ["Carbon Fiber Body", "V12 Engine", "Launch Control", "Carbon Brakes", "Premium Audio"],
        "description": "The Aventador SVJ is the pinnacle of Lamborghini engineering — a track-focused supercar with an unmistakable design and a soul-stirring V12 soundtrack.",
        "horsepower": 770,
        "top_speed": 351,
        "acceleration": "2.8s 0-100 km/h",
    },
    {
        "car_id": "car_rolls_phantom",
        "brand": "Rolls-Royce",
        "model": "Phantom",
        "category": "Luxury",
        "price_per_day": 2200.0,
        "fuel_type": "Petrol",
        "transmission": "Automatic",
        "seats": 5,
        "rating": 5.0,
        "reviews_count": 92,
        "available": True,
        "image": "https://images.pexels.com/photos/11408686/pexels-photo-11408686.jpeg",
        "gallery": [
            "https://images.pexels.com/photos/11408686/pexels-photo-11408686.jpeg",
            "https://images.unsplash.com/photo-1631295868223-63265b40d9e4?w=1200&q=80",
            "https://images.unsplash.com/photo-1612825173281-9a193378527e?w=1200&q=80",
        ],
        "features": ["Starlight Headliner", "Bespoke Interior", "Whisper-Quiet Cabin", "Champagne Cooler", "Chauffeur Mode"],
        "description": "The Phantom redefines luxury. Hand-crafted excellence with the iconic Spirit of Ecstasy guiding every journey.",
        "horsepower": 563,
        "top_speed": 250,
        "acceleration": "5.3s 0-100 km/h",
    },
    {
        "car_id": "car_tesla_plaid",
        "brand": "Tesla",
        "model": "Model S Plaid",
        "category": "Sedan",
        "price_per_day": 890.0,
        "fuel_type": "Electric",
        "transmission": "Automatic",
        "seats": 5,
        "rating": 4.8,
        "reviews_count": 214,
        "available": True,
        "image": "https://images.unsplash.com/photo-1617788138017-80ad40651399?w=1200&q=80",
        "gallery": [
            "https://images.unsplash.com/photo-1617788138017-80ad40651399?w=1200&q=80",
            "https://images.unsplash.com/photo-1560958089-b8a1929cea89?w=1200&q=80",
            "https://images.unsplash.com/photo-1571127236794-81c0bbfe1ce4?w=1200&q=80",
        ],
        "features": ["Autopilot", "Yoke Steering", "21\" Arachnid Wheels", "1020 HP", "Glass Roof"],
        "description": "The quickest production car ever built. Tri-motor all-wheel drive with unmatched electric performance.",
        "horsepower": 1020,
        "top_speed": 322,
        "acceleration": "2.1s 0-100 km/h",
    },
    {
        "car_id": "car_bentley_continental",
        "brand": "Bentley",
        "model": "Continental GT",
        "category": "Luxury",
        "price_per_day": 1350.0,
        "fuel_type": "Petrol",
        "transmission": "Automatic",
        "seats": 4,
        "rating": 4.9,
        "reviews_count": 76,
        "available": True,
        "image": "https://images.unsplash.com/photo-1631295868785-9e5cdf8e0d34?w=1200&q=80",
        "gallery": [
            "https://images.unsplash.com/photo-1631295868785-9e5cdf8e0d34?w=1200&q=80",
            "https://images.unsplash.com/photo-1606664515524-ed2f786a0bd6?w=1200&q=80",
            "https://images.unsplash.com/photo-1606664922998-f180b39ca42f?w=1200&q=80",
        ],
        "features": ["Diamond-Quilted Leather", "Rotating Display", "Naim Audio", "W12 Engine", "All-Wheel Drive"],
        "description": "A grand tourer with razor-sharp performance and hand-stitched British craftsmanship.",
        "horsepower": 626,
        "top_speed": 333,
        "acceleration": "3.5s 0-100 km/h",
    },
    {
        "car_id": "car_porsche_911",
        "brand": "Porsche",
        "model": "911 Turbo S",
        "category": "Sports",
        "price_per_day": 1180.0,
        "fuel_type": "Petrol",
        "transmission": "Automatic",
        "seats": 4,
        "rating": 4.9,
        "reviews_count": 156,
        "available": True,
        "image": "https://images.unsplash.com/photo-1503376780353-7e6692767b70?w=1200&q=80",
        "gallery": [
            "https://images.unsplash.com/photo-1503376780353-7e6692767b70?w=1200&q=80",
            "https://images.unsplash.com/photo-1611821064430-0d40291922d2?w=1200&q=80",
            "https://images.unsplash.com/photo-1611858902246-a3da8eddb16f?w=1200&q=80",
        ],
        "features": ["Sport Chrono Package", "Carbon Ceramic Brakes", "Active Aero", "PASM Suspension", "Bose Audio"],
        "description": "Iconic silhouette, surgical precision. The 911 Turbo S is engineering perfection.",
        "horsepower": 640,
        "top_speed": 330,
        "acceleration": "2.7s 0-100 km/h",
    },
    {
        "car_id": "car_ferrari_sf90",
        "brand": "Ferrari",
        "model": "SF90 Stradale",
        "category": "Sports",
        "price_per_day": 1620.0,
        "fuel_type": "Hybrid",
        "transmission": "Automatic",
        "seats": 2,
        "rating": 4.9,
        "reviews_count": 84,
        "available": False,
        "image": "https://images.unsplash.com/photo-1592198084033-aade902d1aae?w=1200&q=80",
        "gallery": [
            "https://images.unsplash.com/photo-1592198084033-aade902d1aae?w=1200&q=80",
            "https://images.unsplash.com/photo-1583121274602-3e2820c69888?w=1200&q=80",
        ],
        "features": ["Hybrid V8", "eManettino", "Carbon Wheels", "Manettino Dial", "Active Aero"],
        "description": "Ferrari's first plug-in hybrid supercar. 1000 horsepower of pure Italian fury.",
        "horsepower": 1000,
        "top_speed": 340,
        "acceleration": "2.5s 0-100 km/h",
    },
    {
        "car_id": "car_rangerover_autobiography",
        "brand": "Range Rover",
        "model": "Autobiography",
        "category": "SUV",
        "price_per_day": 780.0,
        "fuel_type": "Petrol",
        "transmission": "Automatic",
        "seats": 7,
        "rating": 4.7,
        "reviews_count": 198,
        "available": True,
        "image": "https://images.unsplash.com/photo-1606664515524-ed2f786a0bd6?w=1200&q=80",
        "gallery": [
            "https://images.unsplash.com/photo-1606664515524-ed2f786a0bd6?w=1200&q=80",
            "https://images.unsplash.com/photo-1519440990907-7b4f7e5c0fa9?w=1200&q=80",
            "https://images.unsplash.com/photo-1612825173281-9a193378527e?w=1200&q=80",
        ],
        "features": ["Terrain Response 2", "Meridian Audio", "Massage Seats", "Air Suspension", "Pano Roof"],
        "description": "The ultimate luxury SUV. Commanding presence with off-road capability and refined comfort.",
        "horsepower": 523,
        "top_speed": 250,
        "acceleration": "4.6s 0-100 km/h",
    },
    {
        "car_id": "car_mercedes_maybach",
        "brand": "Mercedes-Maybach",
        "model": "S 680",
        "category": "Luxury",
        "price_per_day": 1280.0,
        "fuel_type": "Petrol",
        "transmission": "Automatic",
        "seats": 4,
        "rating": 4.9,
        "reviews_count": 67,
        "available": True,
        "image": "https://images.unsplash.com/photo-1631295868223-63265b40d9e4?w=1200&q=80",
        "gallery": [
            "https://images.unsplash.com/photo-1631295868223-63265b40d9e4?w=1200&q=80",
            "https://images.unsplash.com/photo-1606664922998-f180b39ca42f?w=1200&q=80",
        ],
        "features": ["Executive Rear Seats", "Burmester 4D Audio", "Two-Tone Paint", "Champagne Flutes", "Hot Stone Massage"],
        "description": "Mobile sanctuary with first-class rear accommodations and bespoke detailing.",
        "horsepower": 621,
        "top_speed": 250,
        "acceleration": "4.4s 0-100 km/h",
    },
    {
        "car_id": "car_aston_db11",
        "brand": "Aston Martin",
        "model": "DB11 V12",
        "category": "Sports",
        "price_per_day": 1340.0,
        "fuel_type": "Petrol",
        "transmission": "Automatic",
        "seats": 4,
        "rating": 4.8,
        "reviews_count": 54,
        "available": True,
        "image": "https://images.unsplash.com/photo-1611821064430-0d40291922d2?w=1200&q=80",
        "gallery": [
            "https://images.unsplash.com/photo-1611821064430-0d40291922d2?w=1200&q=80",
            "https://images.unsplash.com/photo-1611858902246-a3da8eddb16f?w=1200&q=80",
        ],
        "features": ["Hand-Stitched Leather", "Bang & Olufsen Audio", "Adaptive Damping", "Carbon Trim", "Aero Blade"],
        "description": "British grand tourer with timeless elegance and a thunderous twin-turbo V12.",
        "horsepower": 630,
        "top_speed": 322,
        "acceleration": "3.7s 0-100 km/h",
    },
    {
        "car_id": "car_bmw_x7",
        "brand": "BMW",
        "model": "X7 M60i",
        "category": "SUV",
        "price_per_day": 650.0,
        "fuel_type": "Petrol",
        "transmission": "Automatic",
        "seats": 7,
        "rating": 4.6,
        "reviews_count": 142,
        "available": True,
        "image": "https://images.unsplash.com/photo-1606664515524-ed2f786a0bd6?w=1200&q=80",
        "gallery": [
            "https://images.unsplash.com/photo-1606664515524-ed2f786a0bd6?w=1200&q=80",
            "https://images.unsplash.com/photo-1519440990907-7b4f7e5c0fa9?w=1200&q=80",
            "https://images.unsplash.com/photo-1612825173281-9a193378527e?w=1200&q=80",
        ],
        "features": ["BMW iDrive 8", "Crystal Gear Selector", "Sky Lounge Roof", "M Sport Pack", "xDrive AWD"],
        "description": "Flagship BMW SUV with executive presence and athletic performance.",
        "horsepower": 530,
        "top_speed": 250,
        "acceleration": "4.5s 0-100 km/h",
    },
    {
        "car_id": "car_audi_rs7",
        "brand": "Audi",
        "model": "RS7 Sportback",
        "category": "Sedan",
        "price_per_day": 720.0,
        "fuel_type": "Petrol",
        "transmission": "Automatic",
        "seats": 5,
        "rating": 4.7,
        "reviews_count": 109,
        "available": True,
        "image": "https://images.unsplash.com/photo-1606664922998-f180b39ca42f?w=1200&q=80",
        "gallery": [
            "https://images.unsplash.com/photo-1606664922998-f180b39ca42f?w=1200&q=80",
            "https://images.unsplash.com/photo-1611821064430-0d40291922d2?w=1200&q=80",
            "https://images.unsplash.com/photo-1611858902246-a3da8eddb16f?w=1200&q=80",
        ],
        "features": ["Quattro AWD", "Virtual Cockpit", "RS Sport Exhaust", "Bang & Olufsen 3D", "Carbon Pack"],
        "description": "Four-door fastback with brutal acceleration and refined daily usability.",
        "horsepower": 591,
        "top_speed": 305,
        "acceleration": "3.5s 0-100 km/h",
    },
    {
        "car_id": "car_mclaren_720s",
        "brand": "McLaren",
        "model": "720S",
        "category": "Sports",
        "price_per_day": 1520.0,
        "fuel_type": "Petrol",
        "transmission": "Automatic",
        "seats": 2,
        "rating": 4.9,
        "reviews_count": 71,
        "available": True,
        "image": "https://images.unsplash.com/photo-1607853202273-797f1c22a38e?w=1200&q=80",
        "gallery": [
            "https://images.unsplash.com/photo-1607853202273-797f1c22a38e?w=1200&q=80",
            "https://images.unsplash.com/photo-1503376780353-7e6692767b70?w=1200&q=80",
            "https://images.unsplash.com/photo-1592198084033-aade902d1aae?w=1200&q=80",
        ],
        "features": ["Dihedral Doors", "Carbon Monocage", "Active Suspension", "Proactive Chassis", "Track Mode"],
        "description": "British engineering at its lightest and fastest. Pure driver focus.",
        "horsepower": 710,
        "top_speed": 341,
        "acceleration": "2.9s 0-100 km/h",
    },
    {
        "car_id": "car_lambo_huracan",
        "brand": "Lamborghini",
        "model": "Huracán EVO",
        "category": "Sports",
        "price_per_day": 1280.0,
        "fuel_type": "Petrol",
        "transmission": "Automatic",
        "seats": 2,
        "rating": 4.8,
        "reviews_count": 102,
        "available": True,
        "image": "https://images.unsplash.com/photo-1621135802920-133df287f89c?w=1200&q=80",
        "gallery": [
            "https://images.unsplash.com/photo-1621135802920-133df287f89c?w=1200&q=80",
            "https://images.unsplash.com/photo-1544829099-b9a0c07fad1a?w=1200&q=80",
        ],
        "features": ["LDVI System", "ANIMA Modes", "Naturally Aspirated V10", "Magnetorheological Suspension", "Carbon Aero"],
        "description": "The everyday supercar. Razor-sharp on Great Ocean Road, refined on Collins Street.",
        "horsepower": 631,
        "top_speed": 325,
        "acceleration": "2.9s 0-100 km/h",
    },
    {
        "car_id": "car_rolls_ghost",
        "brand": "Rolls-Royce",
        "model": "Ghost Black Badge",
        "category": "Luxury",
        "price_per_day": 1850.0,
        "fuel_type": "Petrol",
        "transmission": "Automatic",
        "seats": 5,
        "rating": 4.9,
        "reviews_count": 58,
        "available": True,
        "image": "https://images.unsplash.com/photo-1631295868223-63265b40d9e4?w=1200&q=80",
        "gallery": [
            "https://images.unsplash.com/photo-1631295868223-63265b40d9e4?w=1200&q=80",
            "https://images.unsplash.com/photo-1612825173281-9a193378527e?w=1200&q=80",
        ],
        "features": ["Black Badge Trim", "Planar Suspension", "Bespoke Audio", "Coach Doors", "Illuminated Spirit"],
        "description": "The darker, more powerful Ghost. Engineered for the rebel within.",
        "horsepower": 600,
        "top_speed": 250,
        "acceleration": "4.6s 0-100 km/h",
    },
    {
        "car_id": "car_tesla_roadster",
        "brand": "Tesla",
        "model": "Roadster",
        "category": "Sports",
        "price_per_day": 1420.0,
        "fuel_type": "Electric",
        "transmission": "Automatic",
        "seats": 4,
        "rating": 4.7,
        "reviews_count": 49,
        "available": True,
        "image": "https://images.unsplash.com/photo-1560958089-b8a1929cea89?w=1200&q=80",
        "gallery": [
            "https://images.unsplash.com/photo-1560958089-b8a1929cea89?w=1200&q=80",
            "https://images.unsplash.com/photo-1571127236794-81c0bbfe1ce4?w=1200&q=80",
        ],
        "features": ["Quad Motor AWD", "Removable Glass Roof", "1000 km Range", "SpaceX Package", "0-100 in 1.9s"],
        "description": "Silent fury. The next-gen Roadster rewrites every benchmark.",
        "horsepower": 1200,
        "top_speed": 400,
        "acceleration": "1.9s 0-100 km/h",
    },
    {
        "car_id": "car_genesis_g90",
        "brand": "Genesis",
        "model": "G90 Long Wheelbase",
        "category": "Sedan",
        "price_per_day": 560.0,
        "fuel_type": "Petrol",
        "transmission": "Automatic",
        "seats": 4,
        "rating": 4.6,
        "reviews_count": 41,
        "available": True,
        "image": "https://images.unsplash.com/photo-1606664922998-f180b39ca42f?w=1200&q=80",
        "gallery": [
            "https://images.unsplash.com/photo-1606664922998-f180b39ca42f?w=1200&q=80",
            "https://images.unsplash.com/photo-1631295868223-63265b40d9e4?w=1200&q=80",
            "https://images.unsplash.com/photo-1606664922998-f180b39ca42f?w=1200&q=80",
        ],
        "features": ["Reclining Rear Seats", "Mood Curator", "23-Speaker Lexicon", "Twin-Turbo V6", "Active Noise Cancellation"],
        "description": "Korean luxury redefined. Executive presence at a connoisseur's price.",
        "horsepower": 409,
        "top_speed": 250,
        "acceleration": "5.0s 0-100 km/h",
    },
    {
        "car_id": "car_porsche_taycan",
        "brand": "Porsche",
        "model": "Taycan Turbo S",
        "category": "Sedan",
        "price_per_day": 940.0,
        "fuel_type": "Electric",
        "transmission": "Automatic",
        "seats": 4,
        "rating": 4.8,
        "reviews_count": 88,
        "available": True,
        "image": "https://images.unsplash.com/photo-1611821064430-0d40291922d2?w=1200&q=80",
        "gallery": [
            "https://images.unsplash.com/photo-1611821064430-0d40291922d2?w=1200&q=80",
            "https://images.unsplash.com/photo-1617788138017-80ad40651399?w=1200&q=80",
            "https://images.unsplash.com/photo-1611858902246-a3da8eddb16f?w=1200&q=80",
        ],
        "features": ["800V Architecture", "Performance Battery+", "PSM Stability", "Adaptive Air Suspension", "Sport+ Mode"],
        "description": "Porsche's electric flagship. Track-bred power meets daily refinement.",
        "horsepower": 750,
        "top_speed": 260,
        "acceleration": "2.6s 0-100 km/h",
    },
    {
        "car_id": "car_lexus_lx",
        "brand": "Lexus",
        "model": "LX 600 Ultra Luxury",
        "category": "SUV",
        "price_per_day": 720.0,
        "fuel_type": "Petrol",
        "transmission": "Automatic",
        "seats": 7,
        "rating": 4.7,
        "reviews_count": 63,
        "available": True,
        "image": "https://images.unsplash.com/photo-1519440990907-7b4f7e5c0fa9?w=1200&q=80",
        "gallery": [
            "https://images.unsplash.com/photo-1519440990907-7b4f7e5c0fa9?w=1200&q=80",
            "https://images.unsplash.com/photo-1606664515524-ed2f786a0bd6?w=1200&q=80",
            "https://images.unsplash.com/photo-1612825173281-9a193378527e?w=1200&q=80",
        ],
        "features": ["Mark Levinson Audio", "Semi-Aniline Leather", "Multi-Terrain Select", "Crawl Control", "Executive Rear"],
        "description": "Bulletproof reliability with first-class accommodations. Mornington Peninsula approved.",
        "horsepower": 409,
        "top_speed": 210,
        "acceleration": "6.9s 0-100 km/h",
    },
    {
        "car_id": "car_maserati_mc20",
        "brand": "Maserati",
        "model": "MC20",
        "category": "Sports",
        "price_per_day": 1390.0,
        "fuel_type": "Petrol",
        "transmission": "Automatic",
        "seats": 2,
        "rating": 4.8,
        "reviews_count": 37,
        "available": True,
        "image": "https://images.unsplash.com/photo-1592198084033-aade902d1aae?w=1200&q=80",
        "gallery": [
            "https://images.unsplash.com/photo-1592198084033-aade902d1aae?w=1200&q=80",
            "https://images.unsplash.com/photo-1583121274602-3e2820c69888?w=1200&q=80",
            "https://images.unsplash.com/photo-1503376780353-7e6692767b70?w=1200&q=80",
        ],
        "features": ["Nettuno V6", "Butterfly Doors", "Carbon Monocoque", "MIA Connect", "GT/Sport/Corsa Modes"],
        "description": "Maserati reborn. Italian flair with surgical precision.",
        "horsepower": 621,
        "top_speed": 325,
        "acceleration": "2.9s 0-100 km/h",
    },
]


DEMO_REVIEWS = [
    ("car_lambo_aventador", 5, "Liam Whitmore", "Took the SVJ down to Phillip Island. Sounds like a god. Insanely fast."),
    ("car_lambo_aventador", 5, "Ava Sinclair", "Eyes everywhere on Chapel Street. Worth every dollar."),
    ("car_lambo_aventador", 4, "Marcus Tan", "Brutal acceleration. Hard to live with daily but unforgettable for the weekend."),
    ("car_lambo_aventador", 5, "Isabella Rossi", "Booked it for my brother's 30th. Made the entire night."),
    ("car_rolls_phantom", 5, "James Halloran", "Hired for our St Kilda wedding. Chauffeur experience was flawless."),
    ("car_rolls_phantom", 5, "Sophia Nguyen", "The Starlight Headliner is unreal. Felt like floating through the CBD."),
    ("car_rolls_phantom", 5, "Edward Blackwood", "Whisper-quiet. Best car I've ever sat in. Will book again."),
    ("car_tesla_plaid", 5, "Daniel Park", "Plaid mode on Eastlink — terrifying in the best way."),
    ("car_tesla_plaid", 4, "Chloe Foster", "Super fun and quick. Yoke takes a couple hours to get used to."),
    ("car_tesla_plaid", 5, "Hiroshi Tanaka", "Charged at Crown overnight, picked up next morning. Effortless."),
    ("car_tesla_plaid", 5, "Riley Patel", "Wife loved it. Smooth, quiet, ludicrous."),
    ("car_bentley_continental", 5, "Olivia Hartwell", "Drove Great Ocean Road. The W12 sound through the tunnels — wow."),
    ("car_bentley_continental", 5, "Henry Lambourne", "Diamond-quilted leather feels like a private jet."),
    ("car_bentley_continental", 4, "Grace Devlin", "Heavy car but incredibly stable. Perfect for long drives."),
    ("car_porsche_911", 5, "Lucas Reinhart", "Best handling car I've driven. Took it to Yarra Valley wineries."),
    ("car_porsche_911", 5, "Emma Chen", "0-100 in under 3s. Sport Chrono package is addictive."),
    ("car_porsche_911", 5, "Noah Whitfield", "Iconic. Sounds incredible through Burnley Tunnel."),
    ("car_porsche_911", 4, "Mia Bennett", "Surprisingly comfortable. Daily-drivable supercar."),
    ("car_ferrari_sf90", 5, "Alessandro Conti", "Pure theatre. Manettino in eD is a riot."),
    ("car_ferrari_sf90", 5, "Zara Khalid", "Booked for a corporate event. Showstopper."),
    ("car_rangerover_autobiography", 5, "Charlotte Mitchell", "Took the family to Mornington. Massive, comfortable, regal."),
    ("car_rangerover_autobiography", 5, "Owen Vasquez", "Air suspension makes it glide. Best SUV experience."),
    ("car_rangerover_autobiography", 4, "Sienna Holloway", "Big inside, quiet, beautiful materials."),
    ("car_rangerover_autobiography", 5, "Tristan Ford", "Used the off-road modes at Wilsons Prom. Capable beast."),
    ("car_mercedes_maybach", 5, "Vivienne Pierce", "Rear seats recline like business class. Massage was unexpected luxury."),
    ("car_mercedes_maybach", 5, "Rashid Al-Mansouri", "Pick-up at Tullamarine, dropped at Crown. Felt like royalty."),
    ("car_aston_db11", 5, "Theodore Hayes", "James Bond fantasy fulfilled. V12 sounds biblical."),
    ("car_aston_db11", 4, "Eleanor Whitlock", "Gorgeous. A bit firm on bluestone laneways but beautiful."),
    ("car_bmw_x7", 4, "Connor Reilly", "Massive interior. Drove to Daylesford with 5 friends, plenty of room."),
    ("car_bmw_x7", 5, "Priya Mehta", "M60i is shockingly fast for an SUV. Loved it."),
    ("car_audi_rs7", 5, "Jasper Lindgren", "Quattro grip is unreal. Drove Mt Dandenong, never broke traction."),
    ("car_audi_rs7", 5, "Anika Bose", "Stealth sleeper. Could not believe the speed."),
    ("car_audi_rs7", 4, "Felix Drummond", "591 hp four-door — what's not to love?"),
    ("car_mclaren_720s", 5, "Sebastian Cross", "Dihedral doors at Crown valet — nothing short of an event."),
    ("car_mclaren_720s", 5, "Aisha Whitman", "Light, surgical, incredibly fast. Best track-bred road car."),
    ("car_lambo_huracan", 5, "Ethan Mortimer", "EVO is the perfect everyday-supercar balance. Stunning."),
    ("car_lambo_huracan", 5, "Layla Hartmann", "Sounded amazing on the M1. ANIMA modes are addictive."),
    ("car_lambo_huracan", 4, "Kai Yamamoto", "Tight cabin but every drive is an event."),
    ("car_rolls_ghost", 5, "Benjamin Whitlock", "Black Badge — perfect blend of power and presence."),
    ("car_rolls_ghost", 5, "Madeline Forrester", "The illuminated Spirit of Ecstasy at night... mesmerising."),
    ("car_tesla_roadster", 5, "Caspian Wells", "1.9s 0-100 has to be experienced. Instant teleportation."),
    ("car_tesla_roadster", 4, "Ruby St. Clair", "Crazy quick. Glass roof is a nice touch on Beach Road."),
    ("car_genesis_g90", 4, "Hugo Bellamy", "Underrated luxury. Felt like a Bentley at half the price."),
    ("car_genesis_g90", 5, "Saskia Nordin", "Mood Curator is brilliant. Made the drive to Lorne feel like a spa."),
    ("car_porsche_taycan", 5, "Maxwell Crane", "Track-day toy on a weeknight. Instantaneous torque is addictive."),
    ("car_porsche_taycan", 5, "Indira Suresh", "Charged at Crown in under 25 minutes. Modern luxury done right."),
    ("car_lexus_lx", 5, "Aaron Whitehill", "Took 7 of us to Mt Buller. Comfortable, capable, quiet."),
    ("car_lexus_lx", 4, "Naomi Rashford", "Mark Levinson audio is reference-grade."),
    ("car_maserati_mc20", 5, "Lorenzo Vitale", "Italian theatre with German precision. Sounded incredible."),
    ("car_maserati_mc20", 5, "Aurora Belmont", "Butterfly doors + Mediterranean Blue paint. Heads turned everywhere."),
]
